### PR TITLE
(save) decompiled

### PR DESCRIPTION
**Pull request by MokhaLeee**
Also renamed functions in save part, and made memory map for SRAM in FE6.

### CODE REVIEW

**Comment by StanHash** [comment]
This is great!

Will do a proper review later (I will be in a hurry because school before that) but here are some preliminary notes:

- I don't agree with some formatting. For example, I prefer [Allman style braces](https://en.wikipedia.org/wiki/Indentation_style#Allman_style), and `int * ptr` style pointer declarations (with spaces on both sides of the asterisk).
- inline functions are emitted at the end of a file (no matter where they are defined), which suggests that there is a file split after `GetPidStats`.

This is minor and if I don't find other problems later on I will probably just fix these myself.

**Comment by MokhaLeee** [comment]
> I prefer [Allman style braces](https://en.wikipedia.org/wiki/Indentation_style#Allman_style), and `int * ptr` style pointer declarations

Got it, acturally I prefer Linux kernel coding style, but you are the boss, and I'd fix this issue.




> * inline functions are emitted at the end of a file (no matter where they are defined), which suggests that there is a file split after `GetPidStats`.

Got it.

Later I may force update this PR.

**Comment by StanHash** [comment]
It is less about _what_ I prefer and more about keeping the style consistent within the entire project.

**Comment by MokhaLeee** [comment]
That does not matter, I have completed on polishing and is ready for review.

**Comment by StanHash** [comment]
This is already very good so I'll merge and fix the little things I dislike later myself.

List to fix (putting this here for myself):

- `func()` → `func(void)`
- `lowerCamelCase` → `snake_case`
- `(*ReadSramFast)(...)` → `ReadSramFast(...)`
- `constant == variable` → `variable == constant`
- names

**Comment by MokhaLeee** [comment]
Yeah, I will never mind

**Pull request merged**
